language: cpp
sudo: required
dist: trusty

services:
  - docker

before_script:
  - export ROOTDIR=`pwd`
  - docker-compose rm -f
  - docker-compose pull
  - docker-compose up --build -d

script:
  - docker exec dcore_container pytest tests/non-mpi/*/*.py
  - docker exec dcore_container pytest tests/mpi/*/*.py

after_script:
  - cd ${ROOTDIR}
  - docker cp dcore_container:/home/triqs/src/DCore/html ${ROOTDIR}/dcore_doc
  - docker-compose stop
  - docker-compose rm -f
  - /bin/bash -x ${ROOTDIR}/.travis_scripts/deploy_docs.sh
