#
# DCore -- Integrated DMFT software for correlated electrons
# Copyright (C) 2017 The University of Tokyo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
from dcore.dcore_pre import dcore_pre
from dcore.dcore import dcore
from dcore.dcore_check import dcore_check
# from dcore.tools import h5diff
import numpy

input_ini = "hphi.ini"

dcore_pre(input_ini)
dcore(input_ini)

# A direct comparison of HDF5 file does not work
# h5diff("square.out.h5", "square.out.h5.ref", "dmft_out/Sigma_iw", precision=1e-5)

# Use sigma.dat generated by dcore_check
dcore_check(input_ini, 'check/', 'png', 100)  # generate sigma.dat
sigma = numpy.loadtxt("check/sigma.dat")
sigma_ref = numpy.loadtxt("sigma.dat.ref")
numpy.allclose(sigma, sigma_ref, atol=1e-5)
