name: Build and upload to PyPI

# Triggered a new tag starting with "v" is pushed
on:
  push:
    tags:
      - 'v*'

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build dist
        run: python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.tar.gz
            dist/*.whl
          if-no-files-found: error

  upload_pypi:
    needs: [build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
